MAC COMPAT: use pcap_next_ex and pcap_create for capture interface
based on the original patch 7c6c67b4451d33bef9c6b2d5ac6f00966a93bae3
from alex-chan.

without using this method, mac user get:
error: failed to compile packet filter

since this code works too on other platforms, there's no reason to put
it under ugly #ifdef APPLE's as the original patch did.